name: CD Springboot Prod

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Server Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/SondageMain
            git pull
            docker-compose down
            docker-compose up -d --build
