name: CD Springboot

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/SondageSpringBoot
            git pull
            docker-compose down
            docker-compose up -d --build
