name: Checkstyle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -B -DskipTests=true

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: Upload Checkstyle results
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-results
        path: target/checkstyle-result.xml
