name: Clover Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: reports/jacoco/jacoco.csv
          badges-directory: reports/jacoco

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5
        with:
          folder: reports/jacoco